### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by DFCMK** [DFCMK/Restaurant-blog#14]
As a Site User,  i can log out from the site to ensure the security of my information.

Acceptance Criteria:
- Users should be able to log out from their profiles.
- Logging out should clear the user's session and invalidate their authentication token, ensuring that their information is secure.

Tasks: 
- [x] Implement logout functionality for all users.
- [x] Ensure that the logout option is accessible within the navbar at all time the user is logged in.
- [x] Test the logout functionality to ensure that it successfully logs out the user and clears their session.

**Comment by yoyopietersma** [comment]
it seems i cannot login at my microsoft account since i openede an account at github . help please. I can not use my chatgtp4 anymore.

**Comment by HemetCa** [comment]
I can't log out?
